// Package detect turns the file list of a restored snapshot into a starter
// recipe. It recognizes common self-hosted apps and falls back to sensible
// file assertions, so `restorable init` can write a working recipe instead of
// leaving the user with a blank page. The generated recipe deliberately favors
// checks that pass on a healthy backup with no extra dependencies (files,
// sqlite); Docker-dependent checks are emitted as commented suggestions so the
// very first `restorable test` is green.
package detect

import (
	"fmt"
	"path"
	"regexp"
	"sort"
	"strings"
)

// Suggestion is the result of analyzing a snapshot's files.
type Suggestion struct {
	// RecipeName is a slug for the recipe (detected app or directory name).
	RecipeName string
	// RecipeYAML is the full, comment-annotated recipe file, ready to write.
	RecipeYAML string
	// Findings are human-readable lines describing what was detected, shown
	// by `restorable init`.
	Findings []string
}

var (
	sqliteRe = regexp.MustCompile(`(?i)\.(sqlite3?|db)$`)
	dumpRe   = regexp.MustCompile(`(?i)(\.sql(\.gz)?|\.dump|\.pgc|\.pgdump)$`)
	slugRe   = regexp.MustCompile(`[^a-z0-9-]+`)
)

// Analyze inspects relative file paths (slash-separated, relative to the
// backed-up root, files only) and returns a starter recipe. rootName is the
// basename of the backed-up path, used as a fallback recipe name.
func Analyze(rootName string, relFiles []string) Suggestion {
	set := make(map[string]bool, len(relFiles))
	topDirFiles := map[string]int{}
	var topLevelFiles []string
	for _, f := range relFiles {
		set[f] = true
		if i := strings.IndexByte(f, '/'); i >= 0 {
			topDirFiles[f[:i]]++
		} else {
			topLevelFiles = append(topLevelFiles, f)
		}
	}

	app, findings, sigFiles := detectApp(set, topDirFiles)
	name := app
	if name == "" {
		name = slug(rootName)
	}
	if name == "" {
		name = "backup"
	}

	var checks []string

	// ── files check ──────────────────────────────────────────────────────────
	seen := map[string]bool{}
	var requires []string
	addReq := func(line, key string) {
		if !seen[key] {
			seen[key] = true
			requires = append(requires, line)
		}
	}
	// Detected app's signature files first — the known-critical paths.
	for _, f := range sigFiles {
		addReq(fmt.Sprintf("      - path: %s", f), f)
	}
	for _, f := range importantTopFiles(topLevelFiles) {
		addReq(fmt.Sprintf("      - path: %s", f), f)
	}
	for _, d := range largestDirs(topDirFiles, 5) {
		floor := topDirFiles[d] / 2
		if floor < 1 {
			floor = 1
		}
		addReq(fmt.Sprintf("      - path: %s/\n        min_files: %d", d, floor), d+"/")
	}
	sample := 3
	if len(relFiles) == 0 {
		sample = 1 // keeps the check valid; will fail loudly on an empty backup
	}
	filesCheck := "  - type: files\n"
	if len(requires) > 0 {
		filesCheck += "    require:\n" + strings.Join(requires, "\n") + "\n"
	}
	filesCheck += fmt.Sprintf("    checksum_sample: %d", sample)
	checks = append(checks, filesCheck)
	if len(requires) > 0 {
		findings = append(findings, fmt.Sprintf("files check: %d required path(s)", len(requires)))
	}

	// ── sqlite checks (no Docker, safe, in-process) ──────────────────────────
	sqlites := matching(relFiles, sqliteRe, 3)
	for _, db := range sqlites {
		checks = append(checks, fmt.Sprintf("  - type: sqlite\n    path: %s", db))
		findings = append(findings, "sqlite integrity check: "+db)
	}

	// ── commented database-dump suggestion (needs Docker) ────────────────────
	var commented string
	if dumps := matching(relFiles, dumpRe, 1); len(dumps) > 0 {
		commented += fmt.Sprintf(`
  # A database dump was found. Uncomment to load it into a throwaway
  # container and verify it actually restores (needs Docker). Switch to
  # 'mysql' if this is a mysqldump.
  # - type: postgres
  #   dump: %s
  #   tables:
  #     - name: your_table
  #       min_rows: 1`, dumps[0])
		findings = append(findings, "database dump found (added as a commented suggestion): "+dumps[0])
	}
	if hint := appDockerHint(app); hint != "" {
		commented += hint
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `restorable init`. Edit freely — assert whatever a good\n")
	fmt.Fprintf(&b, "# restore of your backup must contain.\n")
	fmt.Fprintf(&b, "name: %s\n", name)
	fmt.Fprintf(&b, "checks:\n%s\n", strings.Join(checks, "\n"))
	if commented != "" {
		b.WriteString(strings.TrimRight(commented, "\n") + "\n")
	}

	return Suggestion{RecipeName: name, RecipeYAML: b.String(), Findings: findings}
}

// detectApp recognizes known self-hosted apps by signature files, returning
// the app slug, findings, and the signature files worth asserting explicitly.
func detectApp(set map[string]bool, topDirs map[string]int) (app string, findings, sigFiles []string) {
	switch {
	case set["config/config.php"] && topDirs["data"] > 0:
		return "nextcloud",
			[]string{"detected Nextcloud (config/config.php + data/)"},
			[]string{"config/config.php"}
	case set["db.sqlite3"] && (set["rsa_key.pem"] || set["rsa_key.der"] || set["rsa_key"]):
		return "vaultwarden",
			[]string{"detected Vaultwarden (db.sqlite3 + rsa_key)"},
			[]string{"db.sqlite3"}
	case topDirs["library"] > 0 && topDirs["upload"] > 0:
		return "immich",
			[]string{"detected Immich (library/ + upload/)"},
			nil
	}
	return "", nil, nil
}

func appDockerHint(app string) string {
	switch app {
	case "nextcloud":
		return `
  # Strongest check: boot Nextcloud against the restored data (needs Docker).
  # - type: docker-app
  #   image: nextcloud:apache
  #   mount: { restored: ".", at: "/var/www/html" }
  #   ready: { http: "http://localhost:80/status.php", contains: '"installed":true', timeout: 180s }`
	case "immich":
		return `
  # Immich's automatic DB dumps live under backups/ — point a postgres check
  # at your newest dump (gzipped pg_dump is supported directly).`
	}
	return ""
}

// importantTopFiles picks config-like top-level files worth asserting.
func importantTopFiles(files []string) []string {
	important := regexp.MustCompile(`(?i)(^|\.)(config|conf|env|settings|key|pem|der|crt|yaml|yml|json|php|ini|toml)$|^\.env$|config\.`)
	var out []string
	for _, f := range files {
		base := path.Base(f)
		if important.MatchString(base) {
			out = append(out, f)
		}
	}
	sort.Strings(out)
	if len(out) > 5 {
		out = out[:5]
	}
	return out
}

// largestDirs returns up to n top-level directories, most files first.
func largestDirs(dirFiles map[string]int, n int) []string {
	dirs := make([]string, 0, len(dirFiles))
	for d := range dirFiles {
		dirs = append(dirs, d)
	}
	sort.Slice(dirs, func(i, j int) bool {
		if dirFiles[dirs[i]] != dirFiles[dirs[j]] {
			return dirFiles[dirs[i]] > dirFiles[dirs[j]]
		}
		return dirs[i] < dirs[j]
	})
	if len(dirs) > n {
		dirs = dirs[:n]
	}
	return dirs
}

// matching returns up to n paths matching re, in stable order.
func matching(files []string, re *regexp.Regexp, n int) []string {
	var out []string
	for _, f := range files {
		if re.MatchString(f) {
			out = append(out, f)
		}
	}
	sort.Strings(out)
	if len(out) > n {
		out = out[:n]
	}
	return out
}

func slug(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	s = slugRe.ReplaceAllString(s, "-")
	return strings.Trim(s, "-")
}
