package cmd

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/restorable-dev/restorable/agent/internal/config"
	"github.com/restorable-dev/restorable/agent/internal/detect"
	"github.com/restorable-dev/restorable/agent/internal/restic"
)

func newInitCmd() *cobra.Command {
	var (
		repo        string
		passwordEnv string
		outDir      string
		force       bool
		assumeYes   bool
	)
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Set up agent.yaml and a starter recipe by inspecting your backup",
		Long: "Connects to your restic repository, looks at what the latest snapshot\n" +
			"contains, recognizes common apps (Nextcloud, Vaultwarden, Immich, SQLite\n" +
			"databases, SQL dumps), and writes a working agent.yaml and recipe for you.\n" +
			"No account required. Review the files, then run `restorable test`.",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			in := bufio.NewReader(cmd.InOrStdin())

			if repo == "" {
				repo = os.Getenv("RESTIC_REPOSITORY")
			}
			if repo == "" && !assumeYes {
				repo = prompt(in, cmd.OutOrStdout(), "restic repository (path, s3:…, b2:…, sftp:…)", "")
			}
			if repo == "" {
				return fmt.Errorf("no repository given (pass --repo or set RESTIC_REPOSITORY)")
			}
			if passwordEnv == "" {
				passwordEnv = config.DefaultPasswordEnv
			}
			if os.Getenv(passwordEnv) == "" {
				cmd.Printf("\nNote: %s is not set. restic needs the repository password to\n"+
					"connect — export it and re-run, or set password_env in agent.yaml.\n", passwordEnv)
				if os.Getenv(passwordEnv) == "" {
					return fmt.Errorf("repository password not available in %s", passwordEnv)
				}
			}

			runner, err := restic.NewRunner(repo, passwordEnv)
			if err != nil {
				return err
			}
			ctx := cmd.Context()

			cmd.Printf("Connecting to %s …\n", repo)
			snap, err := runner.LatestSnapshot(ctx)
			if err != nil {
				return fmt.Errorf("could not read the repository: %w", err)
			}
			cmd.Printf("Latest snapshot %s from %s\n", snap.ShortID, snap.Time.Format("2006-01-02 15:04"))

			files, err := runner.Ls(ctx, snap.ID)
			if err != nil {
				return fmt.Errorf("could not list snapshot files: %w", err)
			}

			rootName, rel := relativize(snap.Paths, files)
			sug := detect.Analyze(rootName, rel)

			cmd.Printf("\nLooked at %d files. Here's what I found:\n", len(files))
			for _, f := range sug.Findings {
				cmd.Printf("  • %s\n", f)
			}

			recipeName := sug.RecipeName + ".yaml"
			recipePath := filepath.Join(outDir, recipeName)
			cfgPath := filepath.Join(outDir, "agent.yaml")
			for _, p := range []string{cfgPath, recipePath} {
				if _, err := os.Stat(p); err == nil && !force {
					return fmt.Errorf("%s already exists (use --force to overwrite)", p)
				}
			}

			agentYAML := fmt.Sprintf(`# Generated by `+"`restorable init`"+`.
repo: %s
password_env: %s
recipes: [%s]
# schedule: "0 3 * * 0"   # uncomment for `+"`restorable run`"+` (weekly, Sundays 3am)
sandbox:
  dir: ""                 # OS temp dir; point at a bigger volume if needed
`, repo, passwordEnv, recipeName)

			if err := os.WriteFile(recipePath, []byte(sug.RecipeYAML), 0o644); err != nil {
				return fmt.Errorf("write recipe: %w", err)
			}
			if err := os.WriteFile(cfgPath, []byte(agentYAML), 0o644); err != nil {
				return fmt.Errorf("write agent.yaml: %w", err)
			}
			cmd.Printf("\nWrote %s and %s.\n", cfgPath, recipePath)
			cmd.Printf("Review the recipe, then run:  restorable test --config %s\n", cfgPath)

			runNow := assumeYes
			if !assumeYes {
				runNow = confirm(in, cmd.OutOrStdout(), "\nRun the first test now?", true)
			}
			if runNow {
				cmd.Println()
				test := newTestCmd()
				test.SetContext(ctx)
				test.SetOut(cmd.OutOrStdout())
				test.SetErr(cmd.ErrOrStderr())
				test.SetArgs([]string{"--config", cfgPath})
				return test.Execute()
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&repo, "repo", "", "restic repository (default: $RESTIC_REPOSITORY)")
	cmd.Flags().StringVar(&passwordEnv, "password-env", "", "env var holding the repo password (default: RESTIC_PASSWORD)")
	cmd.Flags().StringVarP(&outDir, "out", "o", ".", "directory to write agent.yaml and the recipe into")
	cmd.Flags().BoolVar(&force, "force", false, "overwrite existing agent.yaml / recipe")
	cmd.Flags().BoolVarP(&assumeYes, "yes", "y", false, "non-interactive: accept defaults and run the first test")
	return cmd
}

// relativize converts absolute snapshot file paths to paths relative to the
// backed-up root, and returns the root's basename for naming. When a snapshot
// has one backed-up path (the common case) this strips that prefix.
func relativize(roots, files []string) (rootName string, rel []string) {
	// Longest root first, so nested roots strip correctly.
	sorted := append([]string(nil), roots...)
	for i := range sorted {
		sorted[i] = strings.TrimRight(sorted[i], "/")
	}
	longestFirst(sorted)
	if len(sorted) > 0 {
		rootName = path.Base(sorted[0])
	}
	for _, f := range files {
		trimmed := ""
		for _, r := range sorted {
			if f == r {
				trimmed = ""
				break
			}
			if strings.HasPrefix(f, r+"/") {
				trimmed = strings.TrimPrefix(f, r+"/")
				break
			}
		}
		if trimmed != "" {
			rel = append(rel, trimmed)
		}
	}
	return rootName, rel
}

func longestFirst(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && len(s[j]) > len(s[j-1]); j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}

func prompt(in *bufio.Reader, out io.Writer, label, def string) string {
	if def != "" {
		_, _ = fmt.Fprintf(out, "%s [%s]: ", label, def)
	} else {
		_, _ = fmt.Fprintf(out, "%s: ", label)
	}
	line, _ := in.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return def
	}
	return line
}

func confirm(in *bufio.Reader, out io.Writer, label string, def bool) bool {
	suffix := " [Y/n]: "
	if !def {
		suffix = " [y/N]: "
	}
	_, _ = fmt.Fprint(out, label+suffix)
	line, _ := in.ReadString('\n')
	line = strings.ToLower(strings.TrimSpace(line))
	if line == "" {
		return def
	}
	return line == "y" || line == "yes"
}
